export type GemCard = {
  id: string;
  label: string;
  icon: string;
  detail: string;
  group?: string;
  locationId?: string;
  evidenceGroup?: "사진 기록" | "목격 진술" | "전자 기록" | "단독 진술";
};

export type GemScene = {
  id: string;
  title: string;
  icon: string;
  report: string;
};

export const GEM_HEIST_DATA = {
  locations: [
    { id: "grand-hall", label: "대연회장", icon: "🥂", detail: "샹들리에 아래 긴 테이블이 놓인 공개 구역", group: "공개 구역" },
    { id: "gallery", label: "초상화 갤러리", icon: "🖼️", detail: "오래된 초상화와 좁은 사각지대가 있는 전시 구역", group: "전시 구역" },
    { id: "roof-garden", label: "옥상 정원", icon: "🌙", detail: "달빛과 유리 온실이 이어진 야외 구역", group: "야외 구역" },
    { id: "wine-cellar", label: "와인 저장고", icon: "🍷", detail: "돌계단 아래 서늘하고 어두운 저장 구역", group: "지하 구역" },
    { id: "library", label: "비밀 서재", icon: "📚", detail: "회전 책장과 벽난로가 있는 개인 구역", group: "개인 구역" },
    { id: "music-room", label: "음악실", icon: "🎹", detail: "그랜드피아노와 방음문이 있는 공연 구역", group: "공개 구역" },
    { id: "kitchen", label: "호텔 주방", icon: "🍽️", detail: "분주한 조리대와 직원 출입문이 있는 업무 구역", group: "업무 구역" },
    { id: "terrace", label: "분수 테라스", icon: "⛲", detail: "정원으로 이어지는 넓은 야외 테라스", group: "야외 구역" },
    { id: "security", label: "보안 관제실", icon: "📹", detail: "감시 화면과 출입 기록 장치가 있는 통제 구역", group: "업무 구역" },
    { id: "dressing", label: "귀빈 분장실", icon: "🪞", detail: "커다란 거울과 의상장이 있는 개인 구역", group: "개인 구역" },
    { id: "elevator", label: "금빛 엘리베이터", icon: "🛗", detail: "각 층을 잇는 좁고 밝은 이동 구역", group: "이동 구역" },
    { id: "atrium", label: "유리 아트리움", icon: "✨", detail: "천장이 유리로 된 밝은 중앙 전시 구역", group: "전시 구역" },
    { id: "boiler", label: "보일러실", icon: "♨️", detail: "배관 소리가 울리는 출입 제한 업무 구역", group: "지하 구역" },
    { id: "archive", label: "지하 기록보관소", icon: "🗄️", detail: "번호표가 붙은 문서함이 빼곡한 지하 구역", group: "지하 구역" },
    { id: "lounge", label: "시가 라운지", icon: "🛋️", detail: "짙은 가죽 소파와 낮은 조명이 있는 개인 구역", group: "개인 구역" },
    { id: "hallway", label: "동쪽 복도", icon: "🚪", detail: "객실과 연회장을 잇는 긴 이동 구역", group: "이동 구역" },
    { id: "loading", label: "후문 하역장", icon: "📦", detail: "배송 차량과 화물 상자가 오가는 업무 구역", group: "업무 구역" },
    { id: "pool", label: "실내 수영장", icon: "🏊", detail: "푸른 조명과 큰 유리창이 있는 공개 구역", group: "공개 구역" },
    { id: "greenhouse", label: "유리 온실", icon: "🌿", detail: "희귀 식물과 젖은 흙냄새가 가득한 야외 구역", group: "야외 구역" },
    { id: "vault-hall", label: "금고 앞 회랑", icon: "🔐", detail: "레이저 센서와 대리석 기둥이 있는 전시 구역", group: "전시 구역" },
  ] satisfies GemCard[],

  stolenItems: [
    { id: "blue-diamond", label: "푸른 달 다이아몬드", icon: "💎", detail: "달빛을 받으면 내부에 별무늬가 떠오르는 88캐럿 보석" },
    { id: "ruby-crown", label: "붉은 왕관", icon: "👑", detail: "사라진 왕조의 루비 일곱 개가 박힌 의식용 왕관" },
    { id: "pearl-necklace", label: "황후의 진주 목걸이", icon: "📿", detail: "크기가 완벽히 같은 진주 서른두 개로 만든 목걸이" },
    { id: "gold-mask", label: "황금 가면", icon: "🎭", detail: "주인의 표정을 닮는다는 전설이 있는 고대 가면" },
    { id: "emerald-brooch", label: "에메랄드 나비 브로치", icon: "🦋", detail: "날개가 미세하게 움직이는 아르누보 보석 장식" },
    { id: "royal-seal", label: "왕실 인장", icon: "🔏", detail: "비밀 문서를 열 수 있는 검은 오팔 인장" },
    { id: "silver-watch", label: "은빛 회중시계", icon: "⌚", detail: "정각마다 숨겨진 음악이 흐르는 정교한 회중시계" },
    { id: "star-sapphire", label: "별빛 사파이어", icon: "🔷", detail: "표면에 여섯 갈래 별이 선명하게 나타나는 원석" },
    { id: "ivory-chess", label: "상아 체스 킹", icon: "♚", detail: "비밀 금고의 열쇠가 숨겨진 단 하나의 체스말" },
    { id: "jade-dragon", label: "비취 용 조각", icon: "🐉", detail: "손바닥만 하지만 왕실 보물로 기록된 비취 조각" },
    { id: "black-opal", label: "검은 불꽃 오팔", icon: "🖤", detail: "각도에 따라 붉은 불꽃이 번지는 희귀 블랙 오팔" },
    { id: "music-box", label: "백조 오르골", icon: "🦢", detail: "세상에 하나뿐인 미완성 왈츠가 담긴 백금 오르골" },
    { id: "sun-tiara", label: "태양의 티아라", icon: "☀️", detail: "노란 다이아몬드가 햇살처럼 배열된 왕실 티아라" },
    { id: "map-scroll", label: "잃어버린 항해지도", icon: "🗺️", detail: "전설의 섬 좌표가 금박으로 기록된 양피지 지도" },
    { id: "crystal-key", label: "수정 열쇠", icon: "🗝️", detail: "어떤 자물쇠를 여는지 알려지지 않은 투명한 열쇠" },
    { id: "phoenix-feather", label: "불사조 깃털 보석", icon: "🪶", detail: "루비와 금실로 깃털의 결까지 재현한 장신구" },
    { id: "moon-ring", label: "월식 반지", icon: "💍", detail: "검은 다이아와 백금이 겹쳐 달의 그림자를 만드는 반지" },
    { id: "mini-portrait", label: "공작부인의 미니어처", icon: "🖼️", detail: "뚜껑 안쪽에 암호가 적힌 손바닥 크기 초상화" },
    { id: "golden-egg", label: "황금 공작알", icon: "🥚", detail: "열면 작은 기계 정원이 펼쳐지는 보석 세공품" },
    { id: "meteor-pin", label: "운석 넥타이핀", icon: "☄️", detail: "실제 운석과 백금으로 만든 단 하나의 넥타이핀" },
  ] satisfies GemCard[],

  tools: [
    { id: "silk-gloves", label: "검은 실크 장갑", icon: "🧤", detail: "지문을 남기지 않는 얇은 맞춤 장갑" },
    { id: "glass-cutter", label: "다이아몬드 유리칼", icon: "🔪", detail: "강화 유리에 소리 없이 원을 그릴 수 있는 도구" },
    { id: "copied-key", label: "복제 황동열쇠", icon: "🗝️", detail: "오래된 자물쇠에 맞춰 급히 깎은 열쇠" },
    { id: "sleep-perfume", label: "수면 향수", icon: "🧴", detail: "잠시 집중력을 흐리게 만드는 달콤한 향수" },
    { id: "wire-hook", label: "극세 와이어 갈고리", icon: "🪝", detail: "좁은 틈 너머의 물건을 끌어당기는 도구" },
    { id: "signal-jammer", label: "초소형 전파 방해기", icon: "📡", detail: "근처 센서와 통신을 잠시 멈추는 장치" },
    { id: "wax-impression", label: "밀랍 열쇠본", icon: "🕯️", detail: "열쇠 모양이 선명하게 찍힌 붉은 밀랍 조각" },
    { id: "mirror-shard", label: "각도 거울", icon: "🪞", detail: "모퉁이 너머 경비의 움직임을 살피는 작은 거울" },
    { id: "magnet-cane", label: "자석 지팡이", icon: "🦯", detail: "손잡이에 강력한 자석이 숨겨진 신사용 지팡이" },
    { id: "fake-badge", label: "위조 출입 배지", icon: "🪪", detail: "직원 구역을 통과하도록 정교하게 복제한 배지" },
    { id: "smoke-capsule", label: "연막 캡슐", icon: "💨", detail: "깨뜨리면 짧은 시간 짙은 안개가 퍼지는 캡슐" },
    { id: "uv-lamp", label: "자외선 손전등", icon: "🔦", detail: "보이지 않는 보안 표시를 읽는 소형 조명" },
    { id: "rope-launcher", label: "손목 로프 발사기", icon: "🧵", detail: "높은 난간에 가는 로프를 걸 수 있는 장치" },
    { id: "code-notebook", label: "암호 수첩", icon: "📓", detail: "경비 교대와 금고 숫자가 기호로 적힌 수첩" },
    { id: "remote-cloner", label: "리모컨 복제기", icon: "🎛️", detail: "문 개폐 신호를 한 번 저장해 재생하는 장치" },
    { id: "hollow-coin", label: "속 빈 동전", icon: "🪙", detail: "작은 보안 나사를 숨겨 운반할 수 있는 동전" },
    { id: "stethoscope", label: "금고 청진기", icon: "🩺", detail: "다이얼 내부의 미세한 걸림음을 듣는 청진기" },
    { id: "fishing-line", label: "투명 낚싯줄", icon: "🎣", detail: "전시대 잠금핀을 멀리서 당길 수 있는 줄" },
    { id: "ice-spray", label: "급속 냉각 스프레이", icon: "❄️", detail: "금속 센서를 순간적으로 굳게 만드는 냉각제" },
    { id: "music-timer", label: "음악 상자 타이머", icon: "🎶", detail: "정해진 시각에 소리를 내 시선을 돌리는 장치" },
  ] satisfies GemCard[],

  times: [
    { id: "dusk", label: "오후 7시 10분", icon: "🌆", detail: "초대 손님이 막 도착하기 시작한 해 질 무렵" },
    { id: "toast", label: "오후 8시 정각", icon: "🥂", detail: "주최자의 환영 건배가 시작된 순간" },
    { id: "quartet", label: "오후 8시 40분", icon: "🎻", detail: "현악 사중주가 가장 크게 연주되던 때" },
    { id: "blackout", label: "오후 9시 13분", icon: "💡", detail: "건물 전체 조명이 17초간 꺼졌던 순간" },
    { id: "fireworks", label: "오후 9시 50분", icon: "🎆", detail: "모두가 테라스의 불꽃놀이를 바라보던 때" },
    { id: "dessert", label: "오후 10시 20분", icon: "🍰", detail: "디저트 카트가 연회장을 돌기 시작한 순간" },
    { id: "rain", label: "오후 10시 47분", icon: "🌧️", detail: "갑작스러운 소나기로 야외 손님이 이동하던 때" },
    { id: "midnight", label: "자정 3분 전", icon: "🕛", detail: "가면무도회의 마지막 춤이 시작되기 직전" },
    { id: "after-midnight", label: "오전 12시 25분", icon: "🌙", detail: "첫 손님들이 돌아가며 로비가 혼잡해진 때" },
    { id: "dawn", label: "오전 1시 10분", icon: "🕯️", detail: "직원들이 촛불을 정리하던 파티의 끝자락" },
  ] satisfies GemCard[],

  traits: [
    { id: "left-handed", label: "왼손잡이", icon: "✋", detail: "서명과 도구 사용을 주로 왼손으로 한다", group: "행동 특징" },
    { id: "fast-walker", label: "걸음이 빠름", icon: "👟", detail: "사람들 사이를 빠르게 지나가는 습관이 있다", group: "행동 특징" },
    { id: "soft-voice", label: "목소리가 작음", icon: "🤫", detail: "가까이 다가가야 들릴 정도로 조용히 말한다", group: "말투 특징" },
    { id: "laughs-often", label: "자주 웃음", icon: "😄", detail: "긴장하면 오히려 웃음이 많아진다", group: "표정 특징" },
    { id: "eye-contact", label: "눈을 잘 마주침", icon: "👁️", detail: "대화할 때 상대의 시선을 피하지 않는다", group: "표정 특징" },
    { id: "avoids-eyes", label: "시선을 피함", icon: "🙈", detail: "질문을 받으면 잠깐 다른 곳을 바라본다", group: "표정 특징" },
    { id: "meticulous", label: "정리정돈이 철저함", icon: "📐", detail: "물건의 방향과 간격까지 가지런히 맞춘다", group: "습관 특징" },
    { id: "fidgeting", label: "손을 자주 만짐", icon: "🤲", detail: "생각할 때 손가락이나 소매 끝을 만진다", group: "습관 특징" },
    { id: "humming", label: "콧노래를 부름", icon: "🎵", detail: "혼자 있을 때 짧은 멜로디를 반복한다", group: "소리 특징" },
    { id: "perfume", label: "향이 강함", icon: "🌸", detail: "지나간 뒤에도 달콤한 향이 잠시 남는다", group: "감각 특징" },
    { id: "cold-hands", label: "손이 차가움", icon: "🧊", detail: "실내에서도 손끝이 유난히 차갑다", group: "감각 특징" },
    { id: "warm-hands", label: "손이 따뜻함", icon: "🔥", detail: "악수하면 온기가 오래 느껴진다", group: "감각 특징" },
    { id: "quick-answer", label: "대답이 빠름", icon: "⚡", detail: "질문이 끝나기 전에 답을 시작하는 편이다", group: "말투 특징" },
    { id: "long-pause", label: "대답 전 뜸을 들임", icon: "⏳", detail: "항상 몇 초 생각한 뒤 천천히 말한다", group: "말투 특징" },
    { id: "precise-time", label: "시간을 정확히 기억함", icon: "⏱️", detail: "일어난 일을 분 단위로 설명한다", group: "기억 특징" },
    { id: "vague-time", label: "시간 기억이 흐림", icon: "🌫️", detail: "정확한 시각 대신 대략적인 표현을 쓴다", group: "기억 특징" },
    { id: "observant", label: "주변을 잘 관찰함", icon: "🔍", detail: "작은 변화나 사라진 물건을 금방 알아챈다", group: "기억 특징" },
    { id: "direction-sense", label: "방향 감각이 좋음", icon: "🧭", detail: "복잡한 복도에서도 길을 쉽게 찾는다", group: "능력 특징" },
    { id: "bad-direction", label: "길을 자주 헤맴", icon: "🌀", detail: "방을 찾으려다 다른 복도로 가곤 한다", group: "능력 특징" },
    { id: "good-hearing", label: "청력이 좋음", icon: "👂", detail: "먼 곳의 작은 금속음도 잘 듣는다", group: "능력 특징" },
    { id: "afraid-dark", label: "어둠을 무서워함", icon: "🕯️", detail: "조명이 꺼지면 밝은 곳부터 찾는다", group: "감정 특징" },
    { id: "bold", label: "겁이 없음", icon: "🦁", detail: "출입 제한 표지에도 별로 긴장하지 않는다", group: "감정 특징" },
    { id: "curious", label: "호기심이 많음", icon: "❔", detail: "잠긴 문이나 낯선 물건을 그냥 지나치지 못한다", group: "감정 특징" },
    { id: "polite", label: "지나치게 정중함", icon: "🎩", detail: "급한 상황에도 꼬박꼬박 예의를 갖춘다", group: "태도 특징" },
    { id: "impatient", label: "성격이 급함", icon: "💨", detail: "기다리는 것을 싫어하고 먼저 행동한다", group: "태도 특징" },
    { id: "whistles", label: "휘파람을 붐", icon: "🎶", detail: "긴장하면 자신도 모르게 짧게 휘파람을 분다", group: "소리 특징" },
    { id: "sneezes", label: "먼지에 재채기함", icon: "🤧", detail: "오래된 천이나 문서 근처에서 재채기한다", group: "감각 특징" },
    { id: "counts-steps", label: "걸음 수를 셈", icon: "🔢", detail: "복도를 걸을 때 속으로 걸음 수를 센다", group: "습관 특징" },
    { id: "touches-ring", label: "반지를 만짐", icon: "💍", detail: "곤란한 질문을 받으면 손가락의 반지를 돌린다", group: "습관 특징" },
    { id: "folded-arms", label: "팔짱을 자주 낌", icon: "🙅", detail: "대화를 들을 때 자연스럽게 팔짱을 낀다", group: "행동 특징" },
  ] satisfies GemCard[],

  alibis: [
    { id: "toast-photo", label: "건배 사진에 찍혔다", icon: "📸", detail: "환영 건배 순간 단체 사진 뒤편에 있었다", locationId: "grand-hall", evidenceGroup: "사진 기록" },
    { id: "piano-request", label: "피아노 신청곡을 적었다", icon: "🎹", detail: "음악실에서 연주자에게 신청 카드를 건넸다", locationId: "music-room", evidenceGroup: "목격 진술" },
    { id: "dessert-order", label: "디저트를 주문했다", icon: "🍰", detail: "연회장 직원에게 레몬 타르트를 부탁했다", locationId: "grand-hall", evidenceGroup: "목격 진술" },
    { id: "umbrella-help", label: "우산을 정리했다", icon: "☂️", detail: "소나기 직후 동쪽 복도의 젖은 우산을 옮겼다", locationId: "hallway", evidenceGroup: "목격 진술" },
    { id: "phone-call", label: "테라스에서 통화했다", icon: "📱", detail: "분수 소리 때문에 야외에서 짧은 전화를 했다", locationId: "terrace", evidenceGroup: "전자 기록" },
    { id: "lost-earring", label: "분장실에서 귀걸이를 찾았다", icon: "🔎", detail: "분장실 바닥을 살피며 혼자 돌아다녔다", locationId: "dressing", evidenceGroup: "단독 진술" },
    { id: "staff-question", label: "복도에서 직원에게 길을 물었다", icon: "🗺️", detail: "처음 온 건물이라 기록보관소 방향을 물었다", locationId: "hallway", evidenceGroup: "목격 진술" },
    { id: "wine-label", label: "와인 라벨을 구경했다", icon: "🍷", detail: "저장고에서 오래된 빈티지 병을 살펴봤다", locationId: "wine-cellar", evidenceGroup: "단독 진술" },
    { id: "garden-photo", label: "온실 사진을 찍었다", icon: "🌿", detail: "유리 온실의 희귀 난초를 여러 장 촬영했다", locationId: "greenhouse", evidenceGroup: "사진 기록" },
    { id: "coat-check", label: "후문에서 외투 번호표를 받았다", icon: "🧥", detail: "하역장 옆 임시 보관소에서 번호표를 다시 발급받았다", locationId: "loading", evidenceGroup: "전자 기록" },
    { id: "card-game", label: "라운지에서 카드게임을 했다", icon: "🃏", detail: "세 사람과 짧은 카드게임 한 판을 마쳤다", locationId: "lounge", evidenceGroup: "목격 진술" },
    { id: "broken-glass", label: "복도에서 깨진 잔을 치웠다", icon: "🥂", detail: "동쪽 복도에 떨어진 잔 조각을 직원과 함께 정리했다", locationId: "hallway", evidenceGroup: "목격 진술" },
    { id: "watch-fireworks", label: "테라스에서 불꽃놀이를 봤다", icon: "🎆", detail: "대부분의 손님과 분수 테라스에 서 있었다", locationId: "terrace", evidenceGroup: "사진 기록" },
    { id: "mirror-fix", label: "분장실에서 옷을 고쳤다", icon: "🪞", detail: "거울 앞에서 흐트러진 옷매무새를 정리했다", locationId: "dressing", evidenceGroup: "단독 진술" },
    { id: "book-search", label: "서재에서 책을 찾았다", icon: "📚", detail: "주최자가 추천한 오래된 추리소설을 찾았다", locationId: "library", evidenceGroup: "단독 진술" },
    { id: "pool-towel", label: "수영장에 수건을 가져갔다", icon: "🏊", detail: "실내 수영장에 두고 온 물건을 가지러 갔다", locationId: "pool", evidenceGroup: "단독 진술" },
    { id: "elevator-stuck", label: "엘리베이터를 기다렸다", icon: "🛗", detail: "고장 표시가 떠 한동안 층 버튼 앞에 있었다", locationId: "elevator", evidenceGroup: "전자 기록" },
    { id: "delivery-sign", label: "배송 확인서에 서명했다", icon: "📦", detail: "후문 하역장에서 잘못 온 꽃상자를 확인했다", locationId: "loading", evidenceGroup: "전자 기록" },
    { id: "music-listen", label: "음악실에서 현악 연주를 들었다", icon: "🎻", detail: "음악실 문가에서 마지막 곡까지 듣고 있었다", locationId: "music-room", evidenceGroup: "목격 진술" },
    { id: "security-report", label: "관제실에서 분실물을 신고했다", icon: "📹", detail: "보안 관제실에서 잃어버린 지갑을 신고했다", locationId: "security", evidenceGroup: "전자 기록" },
  ] satisfies GemCard[],

  questions: [
    { id: "q01", label: "사건 시각에 정확히 어디에 있었나요?", icon: "🕰️", detail: "장소와 이동 경로를 한 문장으로 답하세요." },
    { id: "q02", label: "그 장소에 당신 말고 누가 있었나요?", icon: "👥", detail: "목격자를 한 명 이상 지목해 보세요." },
    { id: "q03", label: "당신의 알리바이를 증명할 물건은?", icon: "🧾", detail: "사진, 영수증, 소지품처럼 구체적으로 답하세요." },
    { id: "q04", label: "오늘 처음 들어간 장소는 어디인가요?", icon: "🚪", detail: "왜 그곳에 갔는지도 함께 말하세요." },
    { id: "q05", label: "마지막으로 보석을 본 순간은?", icon: "💎", detail: "시간과 주변 사람을 떠올려 보세요." },
    { id: "q06", label: "가장 수상한 알리바이는 누구의 것인가요?", icon: "🕵️", detail: "이유를 짧게 설명하세요." },
    { id: "q07", label: "누구의 말이 앞뒤가 맞지 않나요?", icon: "🧩", detail: "바뀐 부분이 있다면 정확히 지적하세요." },
    { id: "q08", label: "범행 도구를 다룰 수 있을 것 같은 사람은?", icon: "🧤", detail: "느낌이 아니라 지금까지 나온 정보로 답하세요." },
    { id: "q09", label: "정전 순간 무엇을 하고 있었나요?", icon: "💡", detail: "손에 들고 있던 것까지 말하세요." },
    { id: "q10", label: "누군가 급히 이동하는 것을 봤나요?", icon: "👟", detail: "봤다면 방향과 특징을 말하세요." },
    { id: "q11", label: "당신이 숨기고 있는 작은 실수는?", icon: "🤐", detail: "범행과 무관해도 솔직하게 하나 공개하세요." },
    { id: "q12", label: "왼쪽 사람의 알리바이를 믿나요?", icon: "⬅️", detail: "믿는다 또는 의심한다를 이유와 함께 답하세요." },
    { id: "q13", label: "오른쪽 사람에게 한 가지를 다시 묻는다면?", icon: "➡️", detail: "가장 확인하고 싶은 부분을 질문하세요." },
    { id: "q14", label: "사건 직후 가장 먼저 들은 소리는?", icon: "👂", detail: "작은 소리라도 구체적으로 묘사하세요." },
    { id: "q15", label: "사건 현장에서 맡은 냄새가 있었나요?", icon: "🌸", detail: "음식, 향수, 연기 등 무엇이든 답하세요." },
    { id: "q16", label: "당신의 단서가 제외하는 사람은?", icon: "❌", detail: "가능하다면 한 명을 제외하고 이유를 말하세요." },
    { id: "q17", label: "현재 가장 믿을 수 있는 사람은?", icon: "🤝", detail: "그 사람의 어떤 말이 믿음을 줬는지 말하세요." },
    { id: "q18", label: "범인이 거짓말한 장소는 어디일까요?", icon: "🗺️", detail: "후보 장소 하나를 골라 설명하세요." },
    { id: "q19", label: "보석을 숨기기 좋은 장소는 어디인가요?", icon: "🔐", detail: "사건 장소 중 하나를 선택하세요." },
    { id: "q20", label: "지금까지 한 말을 10초 안에 요약하세요.", icon: "⏱️", detail: "장소, 알리바이, 단서를 빠르게 정리하세요." },
    { id: "q21", label: "누구와 정보가 서로 충돌하나요?", icon: "⚡", detail: "두 사람을 골라 충돌하는 내용을 말하세요." },
    { id: "q22", label: "범인은 어떤 특징을 숨기려 할까요?", icon: "🎭", detail: "행동이나 말투에서 하나를 골라 보세요." },
    { id: "q23", label: "당신의 이동 경로를 역순으로 말하세요.", icon: "↩️", detail: "현재 장소부터 사건 직전까지 거꾸로 설명하세요." },
    { id: "q24", label: "사건 중 예상 밖의 사람을 만났나요?", icon: "❗", detail: "누구를 어디서 만났는지 답하세요." },
    { id: "q25", label: "당신이 범인이라면 어떤 거짓말을 할까요?", icon: "🃏", detail: "가장 안전해 보이는 거짓말을 하나 말하세요." },
    { id: "q26", label: "한 사람의 소지품을 검사한다면 누구?", icon: "🎒", detail: "선택한 이유까지 짧게 말하세요." },
    { id: "q27", label: "당신의 알리바이에서 가장 약한 부분은?", icon: "🪫", detail: "스스로 의심받을 만한 부분을 인정하세요." },
    { id: "q28", label: "누가 사건 시간을 잘못 기억하는 것 같나요?", icon: "⌛", detail: "시간 설명이 모호했던 사람을 골라 보세요." },
    { id: "q29", label: "보석이 사라진 사실을 언제 알았나요?", icon: "🚨", detail: "누가 알려줬는지도 함께 답하세요." },
    { id: "q30", label: "사건 전 범행 도구와 비슷한 것을 봤나요?", icon: "🔧", detail: "봤다면 장소와 상태를 말하세요." },
    { id: "q31", label: "범인이 가장 피하고 싶은 질문은?", icon: "❓", detail: "직접 질문을 만들어 한 명에게 물어보세요." },
    { id: "q32", label: "지금 투표한다면 누구를 고르겠나요?", icon: "🗳️", detail: "아직 마음이 바뀔 수 있다는 전제로 답하세요." },
    { id: "q33", label: "당신의 단서는 장소와 관련 있나요?", icon: "📍", detail: "예 또는 아니요 뒤에 가능한 만큼 설명하세요." },
    { id: "q34", label: "당신의 단서는 특징과 관련 있나요?", icon: "👤", detail: "예 또는 아니요 뒤에 가능한 만큼 설명하세요." },
    { id: "q35", label: "아직 공개하지 않은 단서가 있나요?", icon: "📁", detail: "숨긴 이유가 있다면 함께 말하세요." },
    { id: "q36", label: "누가 지나치게 자세히 말하고 있나요?", icon: "🔬", detail: "과하게 준비된 듯한 설명을 찾아보세요." },
    { id: "q37", label: "누가 지나치게 짧게 답하고 있나요?", icon: "🤏", detail: "정보를 피하는 듯한 사람을 골라 보세요." },
    { id: "q38", label: "서로 알리바이를 보증할 두 사람은?", icon: "🔗", detail: "실제로 같은 장소였는지 확인하세요." },
    { id: "q39", label: "사건 시각에 가장 멀리 있던 사람은?", icon: "📏", detail: "사건 장소와 각자의 위치를 비교하세요." },
    { id: "q40", label: "범인이 현장을 떠난 방향은?", icon: "🧭", detail: "지금까지 나온 이동 경로로 추정하세요." },
    { id: "q41", label: "한 명만 진실을 말한다고 가정한다면 누구?", icon: "☝️", detail: "그 한 명을 선택한 이유를 말하세요." },
    { id: "q42", label: "한 명만 거짓말한다고 가정한다면 누구?", icon: "🫵", detail: "현재 가장 모순이 큰 사람을 고르세요." },
    { id: "q43", label: "당신이 들은 단서 중 가장 중요한 것은?", icon: "⭐", detail: "누가 말한 어떤 단서인지 정확히 답하세요." },
    { id: "q44", label: "사건을 한 문장으로 재구성해 보세요.", icon: "📝", detail: "범인 후보, 장소, 도구를 모두 넣어 말하세요." },
    { id: "q45", label: "범인이 공범에게 신호를 보냈다면 무엇일까요?", icon: "📨", detail: "말, 행동, 물건 중 하나로 추측하세요." },
    { id: "q46", label: "당신의 특징이 사건과 무관한 이유는?", icon: "🪪", detail: "프로필 특징을 어떻게 설명할지 말하세요." },
    { id: "q47", label: "지금 한 사람과 단둘이 대화한다면 누구?", icon: "💬", detail: "그 사람에게 확인하고 싶은 것을 말하세요." },
    { id: "q48", label: "첫인상과 지금의 생각이 달라진 사람은?", icon: "🔄", detail: "무엇 때문에 생각이 바뀌었는지 답하세요." },
    { id: "q49", label: "최종 변론: 내가 범인이 아닌 이유는?", icon: "⚖️", detail: "모두 차례대로 15초씩 변론하세요." },
    { id: "q50", label: "마지막 확인: 지목을 바꿀 사람이 있나요?", icon: "🔔", detail: "바꾼다면 새 후보와 결정적 이유를 말하세요." },
  ] satisfies GemCard[],

  backgrounds: [
    { id: "masked-gala", title: "검은 가면의 밤", icon: "🎭", report: "{time}, 가면무도회의 음악이 멈춘 순간 {location}에서 {item}이 사라졌습니다." },
    { id: "last-toast", title: "마지막 건배", icon: "🥂", report: "{time}, 주최자가 잔을 든 사이 {location}의 유리 진열장이 비어 있었습니다. 사라진 것은 {item}입니다." },
    { id: "seventeen-seconds", title: "17초의 암전", icon: "💡", report: "{time}, 불이 꺼진 17초 사이 {location}에서 {item}이 흔적도 없이 사라졌습니다." },
    { id: "silent-quartet", title: "멈춰버린 사중주", icon: "🎻", report: "{time}, 연주가 갑자기 끊겼고 {location}에 전시된 {item}이 사라진 사실이 발견됐습니다." },
    { id: "rain-on-glass", title: "유리창의 빗소리", icon: "🌧️", report: "{time}, 폭우가 유리창을 두드리는 동안 {location}에서 {item}이 도난당했습니다." },
    { id: "blue-envelope", title: "푸른 봉투의 초대", icon: "✉️", report: "익명의 초대장이 도착한 밤, {time}에 {location}에서 {item}이 사라졌습니다." },
    { id: "midnight-waltz", title: "자정의 왈츠", icon: "🕛", report: "{time}, 마지막 왈츠가 시작되자 {location}의 {item}이 모조품으로 바뀌어 있었습니다." },
    { id: "empty-pedestal", title: "빈 전시대", icon: "🏛️", report: "{time}, 경비 순찰이 돌아온 뒤 {location}에는 {item}의 빈 받침대만 남아 있었습니다." },
    { id: "whispered-name", title: "복도에서 들린 이름", icon: "🤫", report: "{time}, 누군가 이름을 속삭인 직후 {location}에서 {item}이 사라졌다는 경보가 울렸습니다." },
    { id: "crimson-footprint", title: "붉은 발자국", icon: "👣", report: "{time}, {location} 바닥에 붉은 발자국 하나와 {item}의 빈 케이스가 발견됐습니다." },
    { id: "broken-chandelier", title: "깨진 샹들리에", icon: "✨", report: "{time}, 샹들리에 장식이 떨어져 모두가 고개를 든 사이 {location}의 {item}이 사라졌습니다." },
    { id: "false-alarm", title: "가짜 화재경보", icon: "🚨", report: "{time}, 거짓 화재경보로 손님들이 이동한 동안 {location}에서 {item}이 도난당했습니다." },
    { id: "white-rose", title: "하얀 장미 한 송이", icon: "🌹", report: "{time}, {location}의 빈 진열장 안에는 {item} 대신 하얀 장미만 놓여 있었습니다." },
    { id: "stopped-clock", title: "멈춘 시계", icon: "⌚", report: "모든 시계가 {time}를 가리킨 채 멈췄고, {location}에서 {item}이 사라졌습니다." },
    { id: "locked-room", title: "잠긴 방의 도난", icon: "🔐", report: "{time}, 안에서 잠긴 {location}을 열자 {item}만 감쪽같이 사라져 있었습니다." },
    { id: "two-shadows", title: "두 개의 그림자", icon: "👥", report: "{time}, 목격자는 {location} 벽에 두 그림자가 겹쳤고 곧 {item}이 사라졌다고 진술했습니다." },
    { id: "champagne-bubbles", title: "샴페인 거품 속 신호", icon: "🍾", report: "{time}, 샴페인 병이 터지는 소리와 함께 {location}의 {item}이 사라졌습니다." },
    { id: "vanishing-photograph", title: "사라진 사진 한 장", icon: "📷", report: "{time}, 파티 사진을 확인하던 중 {location}의 {item}과 한 사람이 동시에 사라진 것이 드러났습니다." },
    { id: "blackout-elevator", title: "멈춘 엘리베이터", icon: "🛗", report: "{time}, 엘리베이터가 멈춰 모두가 혼란스러운 사이 {location}에서 {item}이 도난당했습니다." },
    { id: "frozen-window", title: "서리 낀 창문", icon: "❄️", report: "{time}, {location} 창문에 서리가 번졌고 그 안쪽의 {item}이 사라졌습니다." },
    { id: "unplayed-note", title: "연주되지 않은 음표", icon: "🎹", report: "{time}, 피아노에서 낯선 한 음이 울린 직후 {location}의 {item}이 사라졌습니다." },
    { id: "perfumed-letter", title: "향기 나는 협박장", icon: "🌸", report: "{time}, 향수 냄새가 밴 협박장이 발견됐고 {location}에서 {item}이 사라졌습니다." },
    { id: "mirror-message", title: "거울에 남은 문장", icon: "🪞", report: "{time}, 거울에 '찾을 수 있다면'이라는 문장이 나타난 뒤 {location}의 {item}이 사라졌습니다." },
    { id: "thirteenth-guest", title: "열세 번째 손님", icon: "13", report: "명단에 없는 열세 번째 손님이 목격된 {time}, {location}에서 {item}이 도난당했습니다." },
    { id: "missing-key", title: "사라진 열쇠", icon: "🗝️", report: "{time}, 보관함의 열쇠와 함께 {location}에 있던 {item}이 사라졌습니다." },
    { id: "candle-out", title: "꺼진 촛불", icon: "🕯️", report: "{time}, 마지막 촛불이 꺼진 순간 {location}에서 {item}이 감쪽같이 사라졌습니다." },
    { id: "red-thread", title: "문고리의 붉은 실", icon: "🧵", report: "{time}, {location} 문고리에 붉은 실이 묶였고 안쪽에서 {item}이 사라졌습니다." },
    { id: "snow-globe", title: "눈 내리는 유리구슬", icon: "🔮", report: "{time}, 누군가 유리구슬을 흔든 순간 {location}의 경보가 멈추고 {item}이 사라졌습니다." },
    { id: "second-invitation", title: "두 번째 초대장", icon: "🎟️", report: "{time}, 같은 이름의 초대장이 두 장 발견됐고 {location}에서 {item}이 도난당했습니다." },
    { id: "final-curtain", title: "막이 내린 뒤", icon: "🎬", report: "{time}, 공연의 막이 내려간 뒤 {location}의 조명이 켜지자 {item}은 이미 사라진 뒤였습니다." },
  ] satisfies GemScene[],
} as const;
